name: Continuous Integration

on:
  push:
    branches:
      - dev  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python dependencies
      run: |
        pip install selenium
        pip install pyperclip
    - name: Install Chrome
      run: |
       chmod +x ./tests/installChrome.sh
        ./tests/installChrome.sh
      
    - name: Launch App
      run: npm run dev  

    - name: Test Login
      run: python tests/test_login.py 
    - name: Test Account
      run: python tests/test_account.py  
    - name: Test Projects
      run: python tests/test_projects.py 
    - name: Test Datasets
      run: python tests/test_datasets.py
    - name: Test Playground
      run: python tests/test_playground.py 
    - name: Test Evaluation
      run: python tests/test_evaluation.py 
    - name: Test Monitoring
      run: python tests/test_monitoring.py 


    
    

