name: Continuous Integration

on:
  push:
    branches:
      - dev  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python dependencies
      run: |
        pip install selenium
        pip install pyperclip
      run: |
       chmod +x ./tests/InstallChrome.sh
        ./tests/InstallChrome.sh

    - name: Run unit tests
      run: |
        python tests/login.py 
        python tests/account.py  
        python tests/projects.py 
        python tests/datasets.py
        python tests/playground.py 
        python tests/evaluation.py 
